"""Self-contained private HTML view; no public API route or account write."""

from __future__ import annotations

import json
from pathlib import Path
import shutil


def write_review_page(payload: dict, target: Path, echarts_js: Path) -> Path:
    if not echarts_js.is_file():
        raise FileNotFoundError(f"本地 ECharts 资源缺失: {echarts_js}")
    target.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(echarts_js, target / "echarts.min.js")
    data = json.dumps(payload, ensure_ascii=False, separators=(",", ":"), default=str)
    # JSON is embedded in a script element; prevent a broker name or headline
    # from closing the element and injecting arbitrary JavaScript.
    data = data.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    html = HTML.replace("__REVIEW_DATA__", data)
    page = target / "index.html"
    page.write_text(html, encoding="utf-8")
    return page


HTML = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,">
<title>交易复盘 · StockPlatform</title>
<style>
:root{--bg:#0b1220;--panel:#111c2d;--edge:#2a3a50;--text:#e8eef7;--muted:#9eafc3;--cyan:#3dd9d1;--red:#fb7884;--green:#65d2a2;--gold:#e8bd74}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 "Segoe UI","Microsoft YaHei",sans-serif}button,textarea{font:inherit}button{cursor:pointer}
header{padding:26px 30px 19px;border-bottom:1px solid var(--edge);background:linear-gradient(120deg,#142841,#0b1220 65%)}.eyebrow{letter-spacing:.16em;text-transform:uppercase;color:var(--cyan);font-size:11px;font-weight:700}h1{font-size:27px;margin:4px 0}h2{font-size:17px;margin:0 0 12px}h3{font-size:14px;margin:0 0 8px}.subtitle,.muted{color:var(--muted)}.meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:13px}.pill{padding:4px 10px;border:1px solid var(--edge);border-radius:99px;background:#17263b;font-size:12px}.warn{color:var(--gold);border-color:#775b36}.bad{color:var(--red)}.good{color:var(--green)}main{max-width:1500px;margin:auto;padding:22px 25px 60px}.grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(330px,1fr);gap:18px}.panel{background:var(--panel);border:1px solid var(--edge);border-radius:12px;padding:18px;margin-bottom:18px;min-width:0}.dense{padding:14px 18px}.stack{display:grid;gap:18px}.bar{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.btn{background:#1b3150;border:1px solid #355477;color:var(--text);border-radius:7px;padding:6px 10px}.btn:hover,.btn.active{background:#295472;border-color:var(--cyan)}.btn.active{color:white}.btn.red{border-color:#904b56}.tiny{font-size:12px}.chart{width:100%;height:410px}.chart.small{height:280px}.chart.daily{height:310px}.notice{border-left:3px solid var(--gold);padding:8px 11px;background:#2a2430;color:#eed7b3;margin-top:10px}.event{width:100%;text-align:left;background:#17263b;border:1px solid var(--edge);border-radius:8px;color:var(--text);padding:10px 12px;margin-bottom:8px}.event.active{border-color:var(--cyan);background:#193a49}.event .row{display:flex;justify-content:space-between;gap:10px}.buy{color:var(--red)}.sell{color:var(--green)}.tag{color:var(--muted);font-size:11px}.kv{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.kv>div{background:#18283b;padding:9px 10px;border-radius:6px;min-width:0}.kv b{display:block;font-weight:500;font-size:12px;color:var(--muted)}.kv strong{font-size:15px;font-weight:600}.list{margin:0;padding-left:19px}.list li{margin:5px 0}.hscroll{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:430px}th,td{padding:7px 6px;text-align:left;border-bottom:1px solid var(--edge)}th{color:var(--muted);font-size:12px;font-weight:500}.side{font-weight:700}.space{margin-top:14px}textarea{width:100%;height:110px;resize:vertical;background:#0e1a2a;border:1px solid #40536b;border-radius:7px;color:var(--text);padding:10px}.foot{color:var(--muted);font-size:12px;margin-top:20px}.empty{padding:24px;color:var(--muted);text-align:center;border:1px dashed #526174;border-radius:8px}
@media(max-width:1050px){.grid{grid-template-columns:minmax(0,1fr)}.grid>div{min-width:0}.chart{height:340px}}@media(max-width:650px){header{padding:19px 16px}main{padding:14px}.panel{padding:14px}.kv{grid-template-columns:1fr}.chart{height:280px}}
</style><script src="./echarts.min.js"></script></head><body>
<header><div class="eyebrow">STOCKPLATFORM / PRIVATE TRADE REVIEW</div><h1 id="title"></h1><div class="subtitle" id="subtitle"></div><div class="meta" id="meta"></div></header>
<main><div class="panel dense" id="coverage"></div><div class="grid"><div>
<section class="panel"><div class="bar"><h2>当日量价与大盘</h2><div><button class="btn active" id="viewAll">全日</button> <button class="btn" id="viewBefore">只看选中委托之前</button></div></div><div class="tiny muted">成交标记置于委托时间；淡色竖线为成交价首次触达的推断分钟，均非真实成交时刻。完整走势含事后信息。</div><div id="intraday" class="chart"></div></section>
<section class="panel"><h2>前期形态与后续</h2><div class="tiny muted">日 K 包含复盘日后的行情，属于事后验证；选中委托的当时判断只能使用此前数据。</div><div id="daily" class="chart daily"></div></section>
<section class="panel"><h2>市场与方向背景</h2><div id="market"></div><div id="sector" class="space"></div></section>
<section class="panel"><h2>资金与消息证据</h2><div id="flow"></div><div id="quotes" class="space"></div><div id="news" class="space"></div></section>
</div><div>
<section class="panel"><h2>当日委托与操作</h2><div class="tiny muted">可选中任一成交或撤单逐笔讨论；数据源是用户手动导出的委托流水。</div><div id="events" class="space"></div></section>
<section class="panel"><h2>选中操作：当时能看到什么</h2><div id="focus"></div></section>
<section class="panel"><h2>事后走势 · 不能倒灌决策</h2><div id="hindsight"></div></section>
<section class="panel"><h2>共同复盘记录</h2><div class="tiny muted">先写原始意图，再写当时可用信号、替代操作与下次规则。笔记仅在本页内存中，点“下载笔记”留存，不会写入券商或系统数据库。</div><textarea id="notes" placeholder="当时为什么下单？有无可事先识别的反证？下一次如何改？"></textarea><div class="bar space"><button class="btn" id="export">下载笔记 JSON</button><span class="tiny muted">页面刷新前请下载</span></div></section>
</div></div><div class="foot">本页只读，不连接券商、不下单。成交数量/价格来自导入记录；成交发生分钟若未提供真实成交明细，只作带置信度的推断。资金、板块和消息需核对 available_at，不能视作当时必然已知。</div></main>
<script>const D=__REVIEW_DATA__;
const $=id=>document.getElementById(id), esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=2)=>x===null||x===undefined||x===''?'—':Number(x).toLocaleString('zh-CN',{maximumFractionDigits:d});
const clock=s=>s?new Date(s).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
const ymd=s=>s?String(s).slice(0,10):'—';let selected=D.events.findIndex(e=>e.is_execution);if(selected<0)selected=0;let before=false;
const chart=echarts.init($('intraday'));const dailyChart=echarts.init($('daily'));
$('title').textContent=`${D.name}（${D.symbol}） · ${D.day} 操作复盘`;
$('subtitle').textContent=`账户 ${D.account_key} · ${D.events.length} 笔委托 · ${D.events.filter(e=>e.is_execution).length} 笔有成交 · ${D.bar_source}`;
$('meta').innerHTML=`<span class="pill">事实：委托时间、成交价与数量</span><span class="pill warn">推断：成交分钟</span><span class="pill">复盘：当时信息 / 事后验证分开</span>`;
$('coverage').innerHTML=`<div class="bar"><h2>数据覆盖</h2><span class="tiny muted">个股 ${D.coverage.stock_minute_bars} 根分钟线 · 盘中报价 ${D.coverage.quotes} 条（其中有主力净流入值 ${D.coverage.quotes_with_main_net_inflow} 条）</span></div><div class="tiny muted">${esc(D.time_semantics)}</div>${D.coverage.gaps.length?`<div class="notice"><b>待补数据</b><ul class="list">${D.coverage.gaps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'<div class="tiny good">关键数据覆盖已具备；仍须按各项来源与时间逐笔核验。</div>'}`;
function renderEvents(){ $('events').innerHTML=D.events.map((e,i)=>`<button class="event ${i===selected?'active':''}" data-i="${i}"><div class="row"><span class="side ${e.side==='buy'?'buy':'sell'}">${e.side==='buy'?'B 买入':e.side==='sell'?'S 卖出':esc(e.raw_side)}</span><span>${clock(e.order_at)}</span></div><div class="row tiny"><span>${fmt(e.filled_quantity,0)} / ${fmt(e.order_quantity,0)} 股 · ${fmt(e.fill_price)} 元</span><span>${esc(e.status)}</span></div><div class="tag">${e.is_execution?'有成交 · 委托时间代理':'未成交或撤单'} · ${esc(e.order_number)}</div></button>`).join('');
 document.querySelectorAll('.event').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.i);render()});}
function renderFocus(){const e=D.events[selected], c=e.decision_context||{}, map=e.minute_mapping||{};const at=new Date(e.order_at);
 const priorNews=D.news.filter(n=>new Date(n.available_at)<=at).slice(0,5);
 const priorQuotes=D.quotes.filter(q=>new Date(q.observed_at)<=at).slice(-4);
 const previousFlow=D.moneyflow.filter(m=>new Date(m.available_at)<=at).slice(0,6);
 $('focus').innerHTML=`<div class="kv"><div><b>委托时间 · 事实</b><strong>${clock(e.order_at)}</strong></div><div><b>成交价 / 数量 · 事实</b><strong>${e.is_execution?fmt(e.fill_price)+' / '+fmt(e.filled_quantity,0):'未成交'}</strong></div><div><b>下单前最近分钟收盘</b><strong>${fmt(c.last_price)}</strong></div><div><b>当时已存分钟数</b><strong>${fmt(c.minute_count,0)}</strong></div><div><b>截至该时的成交额加权分钟收盘均值</b><strong>${fmt(c.turnover_weighted_close_so_far,3)}</strong></div><div><b>当时区间相对位置</b><strong>${c.range_position_so_far==null?'—':fmt(c.range_position_so_far*100,1)+'%'}</strong></div><div><b>最近 5 / 15 分钟成交额 · 源单位</b><strong>${fmt(c.last_5_amount,0)} / ${fmt(c.last_15_amount,0)}</strong></div><div><b>成交分钟推断</b><strong>${map.mapped_bar_time?clock(map.mapped_bar_time)+' · '+esc(map.confidence):'无可证映射'}</strong></div></div><div class="notice tiny">分时 K 的可见边界按委托时间截断。分钟 K 是收盘后才能完整知道的，委托所在分钟不算作“当时已知”。成交额加权分钟收盘均值只是代理值，不是交易所 VWAP。${e.is_execution?' 成交分钟是价格触达推断。':''}</div><div class="space"><h3>截至委托时已记录的资金快照</h3>${priorQuotes.length?`<div class="hscroll"><table><tr><th>时间</th><th>来源</th><th>涨幅</th><th>主力净流入</th></tr>${priorQuotes.map(q=>`<tr><td>${clock(q.observed_at)}</td><td>${esc(q.source_name)}</td><td>${fmt(q.pct_change)}%</td><td>${fmt(q.main_net_inflow,0)}</td></tr>`).join('')}</table></div>`:'<div class="muted tiny">无截至该时已记录的盘中资金快照。</div>'}</div><div class="space"><h3>此前已发布的消息</h3>${priorNews.length?`<ul class="list tiny">${priorNews.map(n=>`<li>${esc(n.title)} <span class="muted">${clock(n.available_at)} / ${esc(n.source)}</span></li>`).join('')}</ul>`:'<div class="muted tiny">未找到符合 available_at 的消息，不等于市场无消息。</div>'}</div><div class="space"><h3>此前已可得的日资金记录</h3>${previousFlow.length?`<div class="tiny">${previousFlow.map(m=>`${ymd(m.trading_date)} ${esc(m.source)} ${fmt(m.net_amount,0)}`).join('<br>')}</div>`:'<div class="muted tiny">无符合 available_at 的日资金记录。</div>'}</div>`;}
function renderHindsight(){const e=D.events[selected],out=e.hindsight_from_order_time||{};
 $('hindsight').innerHTML=e.is_execution?`<div class="tiny muted">以下从委托时间和成交价出发估算，不是可执行收益，也没有计入成交时刻不确定性、滑点与费用。</div><div class="hscroll space"><table><tr><th>后续</th><th>收盘变化</th><th>最大上行</th><th>最大下行</th></tr>${[5,15,30,60].map(n=>{const x=out[n];return `<tr><td>${n} 分钟</td><td>${x?fmt(x.close_return_pct)+'%':'—'}</td><td>${x?fmt(x.max_up_pct)+'%':'—'}</td><td>${x?fmt(x.max_down_pct)+'%':'—'}</td></tr>`}).join('')}</table></div>`:'<div class="muted tiny">这笔未成交；不计算假设成交的收益。</div>';}
function relativeSeries(bars,times){if(!bars.length)return times.map(()=>null);const first=Number(bars[0].open);const m=new Map(bars.map(x=>[clock(x.bar_time).slice(0,5),Number(x.close)]));return times.map(t=>m.has(t)?+(100*(m.get(t)/first-1)).toFixed(2):null)}
function renderIntraday(){const e=D.events[selected];let bars=D.bars;if(before)bars=bars.filter(b=>new Date(b.bar_time)<new Date(e.order_at));
 if(!bars.length){chart.clear();$('intraday').style.display='none';return}$('intraday').style.display='block';const times=bars.map(x=>clock(x.bar_time).slice(0,5));const first=Number(bars[0].open);const stock=bars.map(x=>+(100*(Number(x.close)/first-1)).toFixed(2));const benchmarks=Object.entries(D.benchmarks).filter(([,v])=>v.bars.length>100).slice(0,2);
 const anchor=clock(e.order_at).slice(0,5);const idx=times.findIndex(t=>t>=anchor);const markerIndex=idx<0?times.length-1:idx;
 const series=[{name:D.name+' %',type:'line',data:stock,smooth:false,showSymbol:false,lineStyle:{width:2.4,color:'#3dd9d1'},itemStyle:{color:'#3dd9d1'},markPoint:!before||markerIndex>=0?{symbolSize:42,label:{formatter:e.side==='buy'?'B':'S',fontWeight:700,color:'#0b1220'},data:[{coord:[times[markerIndex],stock[markerIndex]],itemStyle:{color:e.side==='buy'?'#fb7884':'#65d2a2'}}]}:undefined},...benchmarks.map(([key,v],i)=>({name:key+' %',type:'line',data:relativeSeries(v.bars,times),showSymbol:false,lineStyle:{width:1.3,type:'dashed',color:i?'#e8bd74':'#8a95f8'},itemStyle:{color:i?'#e8bd74':'#8a95f8'}})),{name:'成交额',type:'bar',xAxisIndex:1,yAxisIndex:1,data:bars.map(x=>Number(x.amount||0)),itemStyle:{color:'#315572'}}];
 chart.setOption({animation:false,backgroundColor:'transparent',color:['#3dd9d1','#8a95f8','#e8bd74'],legend:{top:2,textStyle:{color:'#a9bfd0'},selectedMode:true},tooltip:{trigger:'axis',axisPointer:{type:'cross'},valueFormatter:v=>fmt(v)},grid:[{top:40,bottom:'29%',left:58,right:18},{top:'76%',bottom:30,left:58,right:18}],xAxis:[{type:'category',data:times,boundaryGap:false,axisLabel:{color:'#90a2b7',interval:window.innerWidth<600?59:29},axisLine:{lineStyle:{color:'#425168'}}},{type:'category',gridIndex:1,data:times,axisLabel:{show:false},axisLine:{lineStyle:{color:'#425168'}}}],yAxis:[{type:'value',scale:true,axisLabel:{formatter:'{value}%',color:'#90a2b7'},splitLine:{lineStyle:{color:'#27374b'}}},{type:'value',gridIndex:1,axisLabel:{color:'#90a2b7',formatter:v=>v>=1e8?(v/1e8).toFixed(1)+'亿':v>=1e4?(v/1e4).toFixed(0)+'万':v},splitLine:{show:false}}],series},true);}
function renderDaily(){const bars=D.daily;if(!bars.length){$('daily').innerHTML='<div class="empty">缺少日线数据</div>';return}const dates=bars.map(x=>ymd(x.trading_date));dailyChart.setOption({animation:false,backgroundColor:'transparent',tooltip:{trigger:'axis'},grid:[{left:55,right:16,top:22,bottom:'27%'},{left:55,right:16,top:'78%',bottom:24}],xAxis:[{type:'category',data:dates,axisLabel:{color:'#90a2b7',interval:Math.max(0,Math.floor(dates.length/8)-1)}},{type:'category',gridIndex:1,data:dates,axisLabel:{show:false}}],yAxis:[{scale:true,axisLabel:{color:'#90a2b7'},splitLine:{lineStyle:{color:'#27374b'}}},{gridIndex:1,axisLabel:{color:'#90a2b7'},splitLine:{show:false}}],series:[{name:'日K',type:'candlestick',data:bars.map(x=>[x.open,x.close,x.low,x.high]),itemStyle:{color:'#fb7884',color0:'#65d2a2',borderColor:'#fb7884',borderColor0:'#65d2a2'},markLine:{symbol:'none',label:{formatter:'复盘日'},lineStyle:{color:'#e8bd74',type:'dashed'},data:[{xAxis:D.day}]}},{name:'成交额',type:'bar',xAxisIndex:1,yAxisIndex:1,data:bars.map(x=>x.amount),itemStyle:{color:'#315572'}}]},true)}
function renderMarket(){const rows=D.market.filter(x=>ymd(x.trading_date)<=D.day).slice(0,5);$('market').innerHTML=rows.length?`<h3>大盘近 5 日 · 收盘后记录</h3><div class="hscroll"><table><tr><th>日期</th><th>上涨/下跌</th><th>中位涨幅</th><th>成交额(千元)</th></tr>${rows.map(x=>`<tr><td>${ymd(x.trading_date)}</td><td>${fmt(x.advancers,0)} / ${fmt(x.decliners,0)}</td><td>${fmt(x.median_change_pct)}%</td><td>${fmt(x.total_amount_kcny,0)}</td></tr>`).join('')}</table></div>`:'<div class="empty">暂无大盘汇总</div>';
 $('sector').innerHTML=D.sectors.length?`<h3>该股历史板块映射 · 需核对追溯可靠性</h3><div class="hscroll"><table><tr><th>板块</th><th>最近日期</th><th>涨幅</th><th>净流入 · 源单位</th></tr>${D.sectors.slice(0,12).map(x=>`<tr><td>${esc(x.label)} <span class="muted">${esc(x.taxonomy_key)}</span></td><td>${ymd(x.trading_date)}</td><td>${fmt(x.change_pct)}%</td><td>${fmt(x.net_amount,0)}</td></tr>`).join('')}</table></div><div class="tiny muted">历史归属若为 legacy_unbounded，不可直接当作当时已知；最近板块观测也可能晚于委托时刻。</div>`:'<div class="muted tiny">缺少可核查的板块历史。</div>';}
function renderEvidence(){$('flow').innerHTML=D.moneyflow.length?`<h3>个股日资金流 · 各来源口径不可混加</h3><div class="hscroll"><table><tr><th>日期</th><th>来源</th><th>净流入 · 原始单位</th><th>可用时间</th></tr>${D.moneyflow.slice(0,15).map(x=>`<tr><td>${ymd(x.trading_date)}</td><td>${esc(x.source)}</td><td>${fmt(x.net_amount,0)}</td><td>${clock(x.available_at)}</td></tr>`).join('')}</table></div>`:'<div class="muted tiny">无近期资金流数据。</div>';
 $('quotes').innerHTML=`<h3>盘中资金快照</h3><div class="tiny muted">${D.quotes.length?`${D.quotes.length} 条；逐笔界面只列下单之前已记录的快照。`:'无当日快照；不能从收盘后数据反推当时资金。'}</div>`;
 $('news').innerHTML=`<h3>附近消息</h3>${D.news.length?`<ul class="list tiny">${D.news.slice(0,12).map(x=>`<li>${esc(x.title)} <span class="muted">${ymd(x.available_at)} ${clock(x.available_at)} · ${esc(x.source)}</span></li>`).join('')}</ul>`:'<div class="muted tiny">无已收录消息。无记录不等于无消息。</div>'}`;}
function render(){renderEvents();renderFocus();renderHindsight();renderIntraday()};$('viewAll').onclick=()=>{before=false;$('viewAll').classList.add('active');$('viewBefore').classList.remove('active');renderIntraday()};$('viewBefore').onclick=()=>{before=true;$('viewBefore').classList.add('active');$('viewAll').classList.remove('active');renderIntraday()};$('export').onclick=()=>{const e=D.events[selected],blob=new Blob([JSON.stringify({day:D.day,symbol:D.symbol,event_key:e.event_key,order_at:e.order_at,notes:$('notes').value,exported_at:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sb-review-${D.day}-${D.symbol}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};window.onresize=()=>{chart.resize();dailyChart.resize()};renderDaily();renderMarket();renderEvidence();render();
</script></body></html>'''
