[CmdletBinding()]
param([ValidateSet('list','capture')][string]$Mode='list',[uint32[]]$ProcessIds,[IntPtr]$Hwnd,[string]$OutputPath,[switch]$ShowWithoutActivation,[int]$TemporaryWidth=0,[string]$HelperCacheRoot='G:\StockPlatform\data\broker-capture\bin')
$ErrorActionPreference='Stop'
function Invoke-HiddenNative([string]$File,[string[]]$Arguments,[int]$TimeoutMs=10000){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$File;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments=($Arguments|%{if($_ -match '[\s"]'){ '"'+($_ -replace '"','\\"')+'"' }else{$_}})-join ' ';$p=[Diagnostics.Process]::Start($psi);$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit($TimeoutMs)){try{$p.Kill()}catch{};throw "native timeout: $File"};[pscustomobject]@{ExitCode=$p.ExitCode;StdOut=$o.Result;StdErr=$e.Result}}
$root=$PSScriptRoot; $src=Join-Path $root 'broker-window-capture.cs'; $exe=Join-Path $HelperCacheRoot 'broker-window-capture.exe'; $hashFile="$exe.sha256"; $srcHash=(Get-FileHash $src -Algorithm SHA256).Hash
if (-not (Test-Path $exe) -or -not (Test-Path $hashFile) -or (Get-Content $hashFile -Raw).Trim() -ne $srcHash) { New-Item -ItemType Directory -Force (Split-Path $exe) | Out-Null; $c=Invoke-HiddenNative "$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319\csc.exe" @('/nologo','/target:exe',"/out:$exe",'/r:System.Drawing.dll','/r:System.Web.Extensions.dll',$src); if ($c.ExitCode -ne 0) { throw "C# helper compilation failed: $($c.StdOut) $($c.StdErr)" }; Set-Content $hashFile $srcHash }
if ($Mode -eq 'list') { $r=Invoke-HiddenNative $exe @('--list'); if($r.ExitCode -ne 0){throw $r.StdErr}; $all=$r.StdOut|ConvertFrom-Json; $ids=@($ProcessIds | Where-Object { $_ -gt 0 }); if(-not $ids.Count){$ids=@(Get-Process happ,xiadan -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Id)}; $all | Where-Object { $ids -contains [uint32]$_.pid -and ($_.title -match '网上股票交易系统|同花顺|委托|交易' -or $_.class -match 'Afx|Hexin') } | ConvertTo-Json -Compress; exit 0 }
if (-not $OutputPath) { throw 'OutputPath is required for capture' }
$items = (Invoke-HiddenNative $exe @('--list')).StdOut | ConvertFrom-Json
$lr=Invoke-HiddenNative $exe @('--list'); if($lr.ExitCode -ne 0){throw $lr.StdErr}; $all=$lr.StdOut|ConvertFrom-Json; $targets = if($Hwnd) { @($all | Where-Object { [IntPtr]$_.hwnd -eq $Hwnd -and $_.title -eq '网上股票交易系统5.0' }) } else { @($all | Where-Object { $ProcessIds.Count -eq 1 -and $ProcessIds -contains [uint32]$_.pid -and $_.title -eq '网上股票交易系统5.0' -and $_.rect.width -gt 100 -and $_.rect.height -gt 100 }) }
$receipt="$OutputPath.receipt.json"; $dir=Split-Path -Parent $OutputPath; New-Item -ItemType Directory -Force $dir | Out-Null; Remove-Item -LiteralPath $OutputPath -ErrorAction SilentlyContinue
$when=(Get-Date).ToUniversalTime().ToString('o'); $fgBefore=[int64](Invoke-HiddenNative $exe @('--foreground')).StdOut; $before=$targets | Select-Object -First 1; $originalRect=$before.rect; $base=@{observed_at=$when; targetHWND=if($before){$before.hwnd}else{$null}; targetPID=if($before){$before.pid}else{$null}; targetPath=''; title=if($before){$before.title}else{$null}; class=if($before){$before.class}else{$null}; fullrect=if($before){$before.rect}else{$null}; foregroundBefore=$fgBefore; foregroundAfter=$null; exitCode=$null; fileHash=$null; result='failed'}
try {
  if($targets.Count -ne 1){throw "Expected exactly one validated HWND; found $($targets.Count)"}; if($ProcessIds.Count -gt 0 -and $before.pid -ne [uint32]$ProcessIds[0]){throw 'HWND PID mismatch'}
  try{$base.targetPath=(Get-Process -Id $before.pid -ErrorAction Stop).Path}catch{}
  $identityBefore=($before|ConvertTo-Json -Compress)
  if($base.targetPath -notmatch '(?i)xiadan\.exe$'){throw "Target path is not xiadan.exe: $($base.targetPath)"}
  if($ShowWithoutActivation){ $sr=Invoke-HiddenNative $exe @('--show',"$($before.hwnd)"); if($sr.ExitCode -ne 0){throw "SW_SHOWNOACTIVATE failed: $($sr.StdErr)"}; $all=(Invoke-HiddenNative $exe @('--list')).StdOut|ConvertFrom-Json; $before=@($all | Where-Object {[IntPtr]$_.hwnd -eq [IntPtr]$targets[0].hwnd})[0]; if(-not $before){throw 'HWND disappeared after no-activate show'}; if($before.pid -ne $targets[0].pid -or $before.title -ne $targets[0].title -or $before.class -ne $targets[0].class){throw 'HWND identity changed after show'}; $base.fullrect=$before.rect; $base.title=$before.title; $base.class=$before.class }
  if($TemporaryWidth -gt 0){ $rr=Invoke-HiddenNative $exe @('--resize',"$($before.hwnd)","$TemporaryWidth","$($before.rect.height)"); if($rr.ExitCode -ne 0){throw "temporary resize failed: $($rr.StdErr)"}; $all=(Invoke-HiddenNative $exe @('--list')).StdOut|ConvertFrom-Json; $before=@($all | Where-Object {[IntPtr]$_.hwnd -eq [IntPtr]$targets[0].hwnd})[0]; $base.fullrect=$before.rect }
  $psi=New-Object Diagnostics.ProcessStartInfo; $psi.FileName=$exe; $psi.UseShellExecute=$false; $psi.CreateNoWindow=$true; $psi.Arguments='--capture "'+$before.hwnd+'" "'+$OutputPath+'"'; $p=[Diagnostics.Process]::Start($psi); if(-not $p.WaitForExit(10000)){ $p.Kill(); throw 'PrintWindow timed out after 10 seconds' }; $base.exitCode=$p.ExitCode; if($p.ExitCode -ne 0){throw "PrintWindow helper failed with exit code $($p.ExitCode)"}
  $after=@(((Invoke-HiddenNative $exe @('--list')).StdOut|ConvertFrom-Json)|Where-Object hwnd -eq $before.hwnd)[0]; if(-not $after -or $after.pid -ne $before.pid -or $after.title -ne $before.title -or $after.class -ne $before.class -or ($after.rect|ConvertTo-Json -Compress) -ne ($before.rect|ConvertTo-Json -Compress)){throw 'HWND ownership/title/class/fullrect changed during capture'}; $base.foregroundAfter=[int64](Invoke-HiddenNative $exe @('--foreground')).StdOut; if($base.foregroundAfter -ne $fgBefore){throw 'Foreground window changed during capture'}; $base.fileHash=(Get-FileHash $OutputPath -Algorithm SHA256).Hash; $base.result='success'
} catch { $base.error=$_.Exception.Message; Remove-Item -LiteralPath $OutputPath -ErrorAction SilentlyContinue } finally { if($TemporaryWidth -gt 0 -and $originalRect){$restore=Invoke-HiddenNative $exe @('--resize',"$($before.hwnd)","$($originalRect.width)","$($originalRect.height)"); if($restore.ExitCode -ne 0){$base.error="restore failed: $($restore.StdErr)";$base.result='failed'}}; try{$base.foregroundAfter=[int64](Invoke-HiddenNative $exe @('--foreground')).StdOut}catch{}; $base|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $receipt -Encoding UTF8 }
if($base.result -ne 'success'){throw $base.error}; Get-Item $OutputPath | Select-Object FullName,Length
