#!/usr/bin/env bash
# Export the complete n8n workflow definition set into the repository.
#
# PostgreSQL remains the runtime authority, while this credential-value-free
# export is the auditable/importable source artifact.  The n8n export contains
# credential references (ID/name) needed for wiring, never decrypted values.
# It does not start workflows, call quant APIs, or contact market providers.
set -euo pipefail

compose_root="$(cd "$(dirname "$0")/.." && pwd)"
source_root="$compose_root/workflows/managed"
stamp="$(date -u +%Y%m%d-%H%M%S)"
stage_root="$compose_root/workflows/.managed-${stamp}.partial"
previous_root="$compose_root/workflows/.managed-${stamp}.previous"
container_tmp="/tmp/n8n-workflow-source-${stamp}"
replace_existing=false

if [[ "${1:-}" == "--replace" ]]; then
  replace_existing=true
elif [[ $# -gt 0 ]]; then
  echo "usage: $0 [--replace]" >&2
  exit 2
fi

require() { command -v "$1" >/dev/null || { echo "missing required command: $1" >&2; exit 127; }; }
require docker
require jq

cleanup() {
  docker compose -f "$compose_root/compose.yaml" exec -T n8n rm -rf "$container_tmp" >/dev/null 2>&1 || true
  [[ -d "$stage_root" ]] && rm -rf "$stage_root"
}
trap cleanup EXIT

# Do not overwrite an existing managed source tree without an explicit review.
# `--replace` is allowed only for a tree previously generated by this script;
# it atomically swaps the validated replacement and removes that exact stale
# generated tree, so repository source does not accumulate snapshots.
if [[ -e "$source_root" ]]; then
  if [[ "$replace_existing" != true ]]; then
    echo "managed workflow source already exists: $source_root" >&2
    echo "review its diff, then rerun with --replace to refresh this generated tree" >&2
    exit 2
  fi
  [[ -f "$source_root/.n8n-managed-source" ]] || {
    echo "refusing to replace an unmanaged workflow source tree: $source_root" >&2
    exit 2
  }
fi

mkdir -p "$stage_root/workflows"
docker compose -f "$compose_root/compose.yaml" exec -T n8n mkdir -p "$container_tmp"
docker compose -f "$compose_root/compose.yaml" exec -T n8n n8n export:workflow --backup --output="$container_tmp"
docker compose -f "$compose_root/compose.yaml" cp "n8n:${container_tmp}/." "$stage_root/workflows"

workflow_count=0
while IFS= read -r -d '' workflow_file; do
  jq -e '
    type == "object" and
    (.id | type == "string") and
    (.name | type == "string") and
    (.nodes | type == "array") and
    (.connections | type == "object")
  ' "$workflow_file" >/dev/null
  workflow_count="$((workflow_count + 1))"
done < <(find "$stage_root/workflows" -type f -name '*.json' -print0)
((workflow_count > 0)) || { echo "n8n exported no workflows" >&2; exit 1; }

find "$stage_root/workflows" -type f -name '*.json' -print0 | sort -z | xargs -0 jq -s \
  '[.[] | {id, name, active, versionId}] | sort_by(.name)' > "$stage_root/manifest.json"
printf 'managed-by=scripts/export-n8n-workflow-source.sh\nworkflow-count=%s\n' "$workflow_count" > "$stage_root/.n8n-managed-source"

if [[ -e "$source_root" ]]; then
  mv "$source_root" "$previous_root"
fi
mv "$stage_root" "$source_root"
[[ ! -e "$previous_root" ]] || rm -rf "$previous_root"
trap - EXIT
docker compose -f "$compose_root/compose.yaml" exec -T n8n rm -rf "$container_tmp" >/dev/null 2>&1 || true

printf 'workflow_source=%s\nworkflow_files=%s\n' "$source_root" "$workflow_count"
